### ISSUE TITLE
NPE in recursive setID if  rootObject.eClass().getEIDAttribute is null meaningful error requested

### ISSUE THREAD

**Issue by gg-dim** [geckoprojects-org/org.gecko.emf.persistence#16]
If your root object model misses an attribute flagged as 'id', persisting of containing objects fails with a NPE: 
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.EAttribute.getEType()" because the return value of "org.eclipse.emf.ecore.EClass.getEIDAttribute()" is null
	at org.gecko.emf.repository.helper.RepositoryHelper.setIds(RepositoryHelper.java:284)
	at org.gecko.emf.repository.mongo.impl.AbstractEMFMongoRepository.setIDs(AbstractEMFMongoRepository.java:305)
	at org.gecko.emf.repository.DefaultEMFRepository.attach(DefaultEMFRepository.java:231)
	at org.gecko.emf.repository.DefaultEMFRepository.save(DefaultEMFRepository.java:175)
	at org.gecko.emf.repository.DefaultEMFRepository.save(DefaultEMFRepository.java:253)
	at de.dim.trafficos.trafficlight.component.TLServiceImpl.saveTLModule(TLServiceImpl.java:58)
	at de.dim.trafficos.trafficlight.component.TLServiceImpl.lambda$0(TLServiceImpl.java:97)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.dim.trafficos.trafficlight.component.TLServiceImpl.importTLModules(TLServiceImpl.java:97)
	at de.dim.trafficos.vaadin.views.create.IntersectionSystemCreationView.lambda$0(IntersectionSystemCreationView.java:106)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:222)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:394)
	at com.vaadin.flow.component.upload.Upload.fireUploadSuccess(Upload.java:433)
	at com.vaadin.flow.component.upload.Upload$DefaultStreamVariable.streamingFinished(Upload.java:730)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.streamToReceiver(StreamReceiverHandler.java:533)
```
Some meaningful error message could help to find the broken model.

**Comment by isalvadori** [comment]
Fixed in https://github.com/geckoprojects-org/org.gecko.emf.persistence/tree/issue16-meaningful-msg-when-setid-fails
